.hw Art-por-ta-len
.ss 12 0
.de BP
.IP "\fB\\$1\fP"
..
.
.TH ap2csv 1 "SEP 2021 " ap2csv "User Manuals"
.SH "NAME"
ap2csv \- convert an Artportalen Excel export to CSV
.
.SH "SYNOPSIS"
.B ap2csv
.I file.xlsx
.br
.B ap2csv
<
.I file
.br
.B ap2csv --version
.br
.B ap2csv --help
.
.SH "DESCRIPTION"
.
.B ap2csv
simply converts an Microsoft Excel 2007 (XLSX, OOXML) sheet containing data exported from
.B Artportalen
to a CSV form.
It's not guaranteed to do anything useful to other Excel documents; it assumes
everything interesting is in columns and rows in the first sheet.
It's supposed to be equivalent to
.IP
.ft I
xlsx2csv --sheetname=Test --quoting=all --ignoreempty file
.PP
except that utility fails unexpectedly depending on the exact version of
the utility, and the Python version used.
I got tired of it.
.PP
.B ap2csv
takes a single Excel file as input, or else reads from standard input.
.PP
The output is encoded as
.BR iso8859-1 (1)
(Latin-1).
There are double quotes around the cells, and comma between them:
.IR \[lq]foo\[lq],\[lq]bar\[lq],\[lq]baz\[lq] .
No escaping is applied to cell contents like quotes and commas, since I can't be bothered
to find out what people typically do there. See Eric Raymond's criticism of CSV.
.
.SH "BUGS"
There is little error handling, and I haven't read the specifications for the XLSX format.
I just assume that simple Excel exports like that from Artportalen use simple constructs
and don't vary much.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.PP
The parsing relies on
.I libxml2
and the excellent
.IR libarchive .
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
.
.SH "SEE ALSO"
.BR etiketter (5),
.BR xlsx2csv (1).
.PP
.B Artportalen
.IR \[fo]https://www.artportalen.se/\[fc] .
.br
.B xlsx2csv
.IR \[fo]https://github.com/dilshod/xlsx2csv\[fc] .
.br
Raymond, Eric S.
(2004):
.BR "The Art of Unix Programming" .
